// AUTO-GENERATED by scripts/derive-facets.mjs - do not edit by hand.
// Regenerate: node scripts/derive-facets.mjs
// Powers the instant filter rail (see lib/catalog.ts for the Facets type).

import type { Facets, Insurance } from "@/lib/catalog";

export const CATALOG_FACETS: Record<Insurance, Facets> = {
  "unitedhealthcare": {
    "categories": [
      "manual-wheelchairs",
      "mobility-scooters",
      "power-wheelchairs"
    ],
    "brands": [
      "Aspire",
      "mobilityHQ",
      "Pride Mobility",
      "WHILL"
    ],
    "propellingMethods": [
      "Attendant",
      "Self"
    ],
    "ranges": {
      "lengthMm": {
        "min": 838,
        "max": 1290
      },
      "widthMm": {
        "min": 490,
        "max": 742
      },
      "heightMm": {
        "min": 880,
        "max": 1300
      },
      "weightKg": {
        "min": 9,
        "max": 71
      },
      "safeWorkingLoadKg": {
        "min": 113,
        "max": 273
      }
    }
  },
  "humana": {
    "categories": [
      "falls-prevention-solutions"
    ],
    "brands": [
      "Alerta"
    ],
    "propellingMethods": [],
    "ranges": {}
  }
} as const;
