#!/usr/bin/env node
// ---------------------------------------------------------------------------
// scripts/derive-facets.mjs  —  regenerate lib/catalog-facets.generated.ts
// ---------------------------------------------------------------------------
// The catalog filter rail needs its facet values (categories, brands,
// propelling methods, numeric min/max) BEFORE the product fetch resolves, so
// the rail can paint in the static shell. We derive them per insurance cohort
// from the live API and commit the result.
//
// Run this when the catalog schema or contents change materially:
//
//   node scripts/derive-facets.mjs
//
// Reads AZURE_PRODUCTS_URL / AZURE_PRODUCTS_KEY from .env.local.
// ---------------------------------------------------------------------------

import { readFileSync, writeFileSync } from "node:fs";

const INSURANCES = ["unitedhealthcare", "humana"];
const NUMERIC = [
  ["LengthMm", "lengthMm"],
  ["WidthMm", "widthMm"],
  ["HeightMm", "heightMm"],
  ["WeightKg", "weightKg"],
  ["SafeWorkingLoadKg", "safeWorkingLoadKg"],
];

// load env from .env.local if not already set
if (!process.env.AZURE_PRODUCTS_URL || !process.env.AZURE_PRODUCTS_KEY) {
  try {
    for (const line of readFileSync(
      new URL("../.env.local", import.meta.url),
      "utf8",
    ).split(/\r?\n/)) {
      const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*"?([^"]*)"?\s*$/);
      if (m && !process.env[m[1]]) process.env[m[1]] = m[2];
    }
  } catch {
    /* rely on the environment */
  }
}

const base = process.env.AZURE_PRODUCTS_URL;
const key = process.env.AZURE_PRODUCTS_KEY;
if (!base || !key) {
  console.error(
    "Error: AZURE_PRODUCTS_URL / AZURE_PRODUCTS_KEY not set (expected in .env.local).",
  );
  process.exit(1);
}

const uniqueSorted = (xs) =>
  [...new Set(xs)].filter((x) => x != null).sort((a, b) => String(a).localeCompare(String(b)));

const facetsByInsurance = {};

for (const insurance of INSURANCES) {
  const res = await fetch(`${base}?insurance=${insurance}`, {
    headers: { "x-functions-key": key },
  });
  if (!res.ok) {
    console.error(`  ${insurance}: ${res.status} ${await res.text()}`);
    process.exit(1);
  }
  const { products } = await res.json();

  const ranges = {};
  for (const [raw, camel] of NUMERIC) {
    const values = products
      .map((p) => p[raw])
      .filter((v) => typeof v === "number");
    if (values.length > 0) {
      ranges[camel] = { min: Math.min(...values), max: Math.max(...values) };
    }
  }

  facetsByInsurance[insurance] = {
    categories: uniqueSorted(products.map((p) => p.Category)),
    brands: uniqueSorted(products.map((p) => p.BrandName)),
    propellingMethods: uniqueSorted(products.map((p) => p.PropellingMethod)),
    ranges,
  };
  console.log(
    `  ${insurance.padEnd(18)} ${products.length} products, ` +
      `${facetsByInsurance[insurance].categories.length} categories`,
  );
}

const banner = `// AUTO-GENERATED by scripts/derive-facets.mjs - do not edit by hand.
// Regenerate: node scripts/derive-facets.mjs
// Powers the instant filter rail (see lib/catalog.ts for the Facets type).

import type { Facets, Insurance } from "@/lib/catalog";
`;

const body = `export const CATALOG_FACETS: Record<Insurance, Facets> = ${JSON.stringify(
  facetsByInsurance,
  null,
  2,
)} as const;
`;

const out = new URL("../lib/catalog-facets.generated.ts", import.meta.url);
writeFileSync(out, `${banner}\n${body}`);
console.log(`\nWrote ${out.pathname.replace(/^\//, "")}`);
